arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]
  # arm-variant * tegra requires glibc version which is currently not available.
  # binary glibc 2.29.0 <= recipe glibc 2.28 $PREFIX/bin/nvcc
  # The binary is not compatible with the recipe's glibc pinning.
  # See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#system-requirements
  # Enable this once glibc is available on the main channel.
  #- tegra         # [aarch64]
