arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]
  - tegra         # [aarch64]
# needed to support cf-nvidia-tools
c_stdlib_version:
  - 2.17          # [not aarch64]
  - 2.26          # [aarch64]
  
