arm_variant_type: # [aarch64]
  - sbsa          # [aarch64]
#  - tegra         # [aarch64]

c_compiler_version:    # [linux]
  - 14.3.0             # [linux]
cxx_compiler_version:  # [linux]
  - 14.3.0             # [linux]
